### ISSUE TITLE
First letter of a sentence should be uppercase

### ISSUE THREAD

**Issue by jonschlinkert** [blakeembrey/sentence-case#4]
Hey @blakeembrey, I'd like to use this but noticed that it lowercases the entire string. Here is some info on sentence casing: http://en.wiktionary.org/wiki/sentence_case.

**Comment by blakeembrey** [comment]
Hi @jonschlinkert, unfortunately this module wasn't made for that (I should probably make that clearer in the README, guess I'm bad at naming) and I didn't try to make something for it since it can be quite opinionated. Maybe we can find something that might work for most people? In general this collection of modules were for small easily defined transforms instead of complex rules understanding acronyms and proper nouns. 

A similar issue has been logged https://github.com/blakeembrey/title-case/issues/3 in the past. Let me know the rules you are thinking about and we can try collaborating to get something that works for everyone :+1:

**Comment by jonschlinkert** [comment]
> unfortunately this module wasn't made for that

no prob, I'm not sure what you mean by "that" though. Perhaps I'm missing something obvious, but - with the exclusion of the rare locale - the function returns a string that will **always** be completely lowercased.

> Let me know the rules you are thinking about

No rules of my own per se. I was an English Lit major so I can be a bit of a grammar/syntax nerd, but to my knowledge, there is only "the" rule of sentence case, which is a common qualifying factor that every definition has in common: the first letter of a sentence is always capitalized with the exception of proper nouns and acronyms.  

anyway, no big deal. I'm just trying to decide what to implement, and it sounds like you might know some things that I haven't considered. Just make sure, sounds like you're saying you'd rather code toward the exception (e.g. proper nouns and acronyms) than the rule? If so, perhaps this module should be re-named to something that implies just "lowercase"?

**Comment by blakeembrey** [comment]
@jonschlinkert You're right, though it's not exactly doing just a lower case. Maybe it should have been called `space-case` or something. I can fix this in future with a new major version and bumping all the deps, but it's not urgent right now.

As for the rules, I'm just curious as to it's use case and what you expect to get out of it. Is the input user strings or the same programmatic usage as this? For example, are you trying to solve input of `"the acronym of usa"` becoming stuff like `"The acronym of USA"`. This module is stripping all non-word characters, does that match your use-case?

**Comment by jonschlinkert** [comment]
> but it's not urgent right now.

no worries

> I'm just curious as to it's use case

Really, I was just going to use this for a helper lib to uppercase the first letter of a string, e.g. 

```js
str. charAt(0).toUpperCase() + str.slice(1);
```

I wasn't looking for anything more than that. I know it's a line of code but I'd rather use a (your) module if it does what I need. I don't have any special needs for it at all, was just wanting to clarify. thanks!

**Comment by blakeembrey** [comment]
@jonschlinkert Does this help you? https://github.com/blakeembrey/upper-case-first combined with this may do what you're after (this module does remove all non-word chars though).

**Comment by jonschlinkert** [comment]
Thanks I'll take look!

**Comment by jonschlinkert** [comment]
thanks @blakeembrey. I'm using these in a couple of generators, nice work!

**Comment by stevenvachon** [comment]
"space-case" would make more sense, definitely. "sentence-case" implies capitalization.
