### ISSUE TITLE
last capital letter in camel case string should be start of next word

### ISSUE THREAD

**Issue by UziTech** [blakeembrey/sentence-case#5]
Related to https://github.com/blakeembrey/snake-case/issues/4

The last capital letter in a camel case string with multiple consecutive capital letters should be the start of a new word when followed by a lowercase letter.

`anHTMLTag => an html tag`

**Comment by blakeembrey** [comment]
It's not quite that, since it breaks down with constant-case (E.g. `FOO_BAR` should be `foo_bar`). I think it's more like the last capital letter in a sequence of two or more followed by a lowercase letter or number should be split in two. I'll write some tests though.

**Comment by UziTech** [comment]
looks like this will require a new regexp test

`(\\p{Lu}+)([\\p{Lu}\\p{Ll}])`
